package GUI;

import Utils.LoggedIn;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class DriverMenu {
    private JPanel WelcomePanel;
    private JLabel WelcomeLabel;
    private JPanel DriverMenuPanel;
    public JPanel MainPanel;
    private JButton rideHistoryBtn;
    private JButton appRidesBtn;
    private JButton phoneRidesBtn;
    private JButton rideReportsBtn;
    private JButton offerWindowBtn;
    public static JFrame mainMenuWindow;

    public DriverMenu() {

        this.WelcomeLabel.setText("Dobrodosli:  " + (LoggedIn.getLoggedUser().getUsername()));
        mainMenuWindow = new JFrame();
        mainMenuWindow.setTitle("Glavni meni");
        mainMenuWindow.setContentPane(this.MainPanel);
        mainMenuWindow.setLocationRelativeTo(null);
        mainMenuWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mainMenuWindow.pack();

        initActions();
    }

    private void initActions() {
        this.rideHistoryBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openDriveHistroyDialog();
            }
        });

        this.appRidesBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openAppAceptionDialog();
            }
        });

        this.rideReportsBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openRideReportsDialog();
            }
        });

        this.offerWindowBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openOfferDialog();
            }
        });
    }

    private void openDriveHistroyDialog() {
        DriverRideHistoryWindow ridesHistoryDialog = new DriverRideHistoryWindow();
        ridesHistoryDialog.ridesWindow.setVisible(true);

    }

    private void openAppAceptionDialog() {
        AppReservationAcceptWindow acceptWindow = new AppReservationAcceptWindow();
        acceptWindow.ridesWindow.setVisible(true);
    }

    private void openRideReportsDialog() {
        DriverRidesReportWindow ridesReportDialog = new DriverRidesReportWindow();
        ridesReportDialog.reportsWindow.setVisible(true);
    }

    private void openOfferDialog() {
        MakeOfferWindow ridesReportDialog = new MakeOfferWindow();
        ridesReportDialog.ridesWindow.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new BorderLayout(0, 0));
        MainPanel.setPreferredSize(new Dimension(500, 400));
        WelcomePanel = new JPanel();
        WelcomePanel.setLayout(new GridBagLayout());
        WelcomePanel.setPreferredSize(new Dimension(400, 50));
        MainPanel.add(WelcomePanel, BorderLayout.NORTH);
        WelcomeLabel = new JLabel();
        WelcomeLabel.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        WelcomePanel.add(WelcomeLabel, gbc);
        DriverMenuPanel = new JPanel();
        DriverMenuPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        DriverMenuPanel.setPreferredSize(new Dimension(500, 400));
        DriverMenuPanel.setVisible(true);
        MainPanel.add(DriverMenuPanel, BorderLayout.CENTER);
        rideHistoryBtn = new JButton();
        rideHistoryBtn.setPreferredSize(new Dimension(180, 60));
        rideHistoryBtn.setText("Moje voznje");
        DriverMenuPanel.add(rideHistoryBtn);
        appRidesBtn = new JButton();
        appRidesBtn.setPreferredSize(new Dimension(180, 60));
        appRidesBtn.setText("Voznje iz aplikacije");
        DriverMenuPanel.add(appRidesBtn);
        phoneRidesBtn = new JButton();
        phoneRidesBtn.setPreferredSize(new Dimension(180, 60));
        phoneRidesBtn.setText("Voznje preko telefona");
        DriverMenuPanel.add(phoneRidesBtn);
        rideReportsBtn = new JButton();
        rideReportsBtn.setPreferredSize(new Dimension(180, 60));
        rideReportsBtn.setText("Izvestaji");
        DriverMenuPanel.add(rideReportsBtn);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

}
