package GUI;

import GUI.UpdateDialogs.AppReservationDialog;
import Utils.LoggedIn;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class UserMenu {
    private JPanel WelcomePanel;
    private JLabel WelcomeLabel;
    private JPanel UserMenuPanel;
    private JPanel MainPanel;
    private JButton rideHistoryBtn;
    private JButton appReservationBtn;
    public static JFrame mainMenuWindow;

    public UserMenu() {
        this.WelcomeLabel.setText("Dobrodosli:  " + LoggedIn.getLoggedUser().getUsername());
        mainMenuWindow = new JFrame();
        mainMenuWindow.setTitle("Glavni meni");
        mainMenuWindow.setContentPane(this.MainPanel);
        mainMenuWindow.setLocationRelativeTo(null);
        mainMenuWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mainMenuWindow.pack();

        initActions();

    }

    private void initActions() {
        this.rideHistoryBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openDriveHistroyDialog();
            }
        });

        this.appReservationBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openAppReservationDialog();
            }
        });
    }

    private void openDriveHistroyDialog() {
        UserRideHistoryWindow ridesHistoryDialog = new UserRideHistoryWindow();
        ridesHistoryDialog.ridesWindow.setVisible(true);

    }

    private void openAppReservationDialog() {
        AppReservationDialog appReservationDialog = new AppReservationDialog();
        appReservationDialog.appReservationWindow.setVisible(true);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new BorderLayout(0, 0));
        MainPanel.setPreferredSize(new Dimension(500, 400));
        WelcomePanel = new JPanel();
        WelcomePanel.setLayout(new GridBagLayout());
        WelcomePanel.setPreferredSize(new Dimension(400, 50));
        MainPanel.add(WelcomePanel, BorderLayout.NORTH);
        WelcomeLabel = new JLabel();
        WelcomeLabel.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        WelcomePanel.add(WelcomeLabel, gbc);
        UserMenuPanel = new JPanel();
        UserMenuPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        UserMenuPanel.setPreferredSize(new Dimension(500, 400));
        UserMenuPanel.setVisible(true);
        MainPanel.add(UserMenuPanel, BorderLayout.CENTER);
        final JButton button1 = new JButton();
        button1.setPreferredSize(new Dimension(350, 60));
        button1.setText("Naruci telefonsku voznju");
        UserMenuPanel.add(button1);
        appReservationBtn = new JButton();
        appReservationBtn.setPreferredSize(new Dimension(350, 60));
        appReservationBtn.setText("Naruci voznju putem aplikacije");
        UserMenuPanel.add(appReservationBtn);
        rideHistoryBtn = new JButton();
        rideHistoryBtn.setPreferredSize(new Dimension(350, 60));
        rideHistoryBtn.setText("Moje voznje");
        UserMenuPanel.add(rideHistoryBtn);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

}
