package GUI.UpdateDialogs;

import Controllers.ServiceController;
import Entities.TaxiService;
import Repositories.TaxiServiceFileRepository;
import Utils.LoggedIn;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class TaxiServiceData {
    public JPanel ServicePanel;
    private JTextField nameTextField;
    private JTextField AdressTextField;
    private JTextField PriceForKmTextField;
    private JTextField PibTextLabel;
    private JButton updateService;
    private JTextField startingPriceTextField;
    public static JFrame taxiServiceWindow;

    public TaxiServiceData() {
        taxiServiceWindow = new JFrame();
        taxiServiceWindow.setTitle("Izmena informacija o taxi sluzbi");
        taxiServiceWindow.setContentPane(this.ServicePanel);
        taxiServiceWindow.setLocationRelativeTo(null);
        taxiServiceWindow.pack();

        initActions();
    }

    public void fillInData(TaxiService service) {
        this.PibTextLabel.setText(String.valueOf((service.getPib())));
        this.AdressTextField.setText(service.getAddress());
        this.nameTextField.setText(service.getName());
        this.PriceForKmTextField.setText(String.valueOf(service.getPriceForKm()));
        this.startingPriceTextField.setText(String.valueOf(service.getStartingPrice()));

    }

    private void saveData(TaxiService service) {
        if (validation()) {
            ServiceController.UpdateService(service, this.nameTextField.getText().trim(), this.AdressTextField.getText().trim(), Integer.parseInt(this.PriceForKmTextField.getText().trim()), Integer.parseInt(this.startingPriceTextField.getText().trim()));
            TaxiServiceFileRepository.saveService(service);
            JOptionPane.showMessageDialog(null, "Uspesno sacuvani podaci", "Cuvanje podataka", JOptionPane.INFORMATION_MESSAGE);
        }
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ServicePanel = new JPanel();
        ServicePanel.setLayout(new GridBagLayout());
        ServicePanel.setAutoscrolls(false);
        ServicePanel.setName("Izmena podataka sluzbe");
        ServicePanel.setPreferredSize(new Dimension(380, 350));
        final JLabel label1 = new JLabel();
        label1.setText("PIB:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        ServicePanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Ime:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        ServicePanel.add(label2, gbc);
        nameTextField = new JTextField();
        nameTextField.setPreferredSize(new Dimension(180, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 0, 0);
        ServicePanel.add(nameTextField, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Adresa:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        ServicePanel.add(label3, gbc);
        AdressTextField = new JTextField();
        AdressTextField.setPreferredSize(new Dimension(180, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 0, 0);
        ServicePanel.add(AdressTextField, gbc);
        PriceForKmTextField = new JTextField();
        PriceForKmTextField.setPreferredSize(new Dimension(180, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 0, 0);
        ServicePanel.add(PriceForKmTextField, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("CenaPoKm:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.EAST;
        ServicePanel.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("CenaPolaska:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.EAST;
        ServicePanel.add(label5, gbc);
        PibTextLabel = new JTextField();
        PibTextLabel.setEditable(false);
        PibTextLabel.setPreferredSize(new Dimension(180, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 0, 0);
        ServicePanel.add(PibTextLabel, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Informacije o sluzbi");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTH;
        ServicePanel.add(label6, gbc);
        updateService = new JButton();
        updateService.setText("Sacuvaj izmene");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 0, 0);
        ServicePanel.add(updateService, gbc);
        startingPriceTextField = new JTextField();
        startingPriceTextField.setPreferredSize(new Dimension(180, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 0, 0);
        ServicePanel.add(startingPriceTextField, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ServicePanel;
    }

    private boolean validation() {
        boolean isValid = true;
        String message = "Molimo vas ispravite sledece greske prilkom unosa:\n";
        if (this.nameTextField.getText().trim().equals("")) {
            message += "Morate uneti naziv \n";
            isValid = false;
        }
        if (this.AdressTextField.getText().trim().equals("")) {
            message += "Morate uneti adresu \n";
            isValid = false;
        }
        try {
            Integer.parseInt(this.PriceForKmTextField.getText().trim());
            Integer.parseInt(this.startingPriceTextField.getText().trim());
        } catch (NumberFormatException e) {
            message += "Cene moraju biti broj";
            isValid = false;
        }

        if (isValid == false) {
            JOptionPane.showMessageDialog(null, message, "Neispravni podaci", JOptionPane.WARNING_MESSAGE);
        }
        return isValid;
    }

    private void initActions() {
        fillInData(LoggedIn.getService());

        updateService.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                saveData(LoggedIn.getService());
            }
        });
    }
}
